// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomAction(arg1) {
  return window['go']['main']['App']['AddCustomAction'](arg1);
}

export function BrowseSCDir() {
  return window['go']['main']['App']['BrowseSCDir']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectTwitch() {
  return window['go']['main']['App']['ConnectTwitch']();
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteAllRewards() {
  return window['go']['main']['App']['DeleteAllRewards']();
}

export function DisconnectTwitch() {
  return window['go']['main']['App']['DisconnectTwitch']();
}

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function GetBindStatus() {
  return window['go']['main']['App']['GetBindStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCooldownRemaining(arg1) {
  return window['go']['main']['App']['GetCooldownRemaining'](arg1);
}

export function GetDebugLogPath() {
  return window['go']['main']['App']['GetDebugLogPath']();
}

export function GetGlobalEnable() {
  return window['go']['main']['App']['GetGlobalEnable']();
}

export function GetInputMode() {
  return window['go']['main']['App']['GetInputMode']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLockedKeys() {
  return window['go']['main']['App']['GetLockedKeys']();
}

export function GetSCChannel() {
  return window['go']['main']['App']['GetSCChannel']();
}

export function GetSCDir() {
  return window['go']['main']['App']['GetSCDir']();
}

export function GetSCInstalls() {
  return window['go']['main']['App']['GetSCInstalls']();
}

export function GetTwitchApp() {
  return window['go']['main']['App']['GetTwitchApp']();
}

export function GetTwitchChannel() {
  return window['go']['main']['App']['GetTwitchChannel']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportSCBinds() {
  return window['go']['main']['App']['ImportSCBinds']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function IsTwitchConnected() {
  return window['go']['main']['App']['IsTwitchConnected']();
}

export function RemoveSCBinds() {
  return window['go']['main']['App']['RemoveSCBinds']();
}

export function SetGlobalEnable(arg1) {
  return window['go']['main']['App']['SetGlobalEnable'](arg1);
}

export function SetInputMode(arg1) {
  return window['go']['main']['App']['SetInputMode'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetSCDir(arg1) {
  return window['go']['main']['App']['SetSCDir'](arg1);
}

export function SetTargetWindow(arg1) {
  return window['go']['main']['App']['SetTargetWindow'](arg1);
}

export function SetTwitchApp(arg1, arg2) {
  return window['go']['main']['App']['SetTwitchApp'](arg1, arg2);
}

export function StartTwitchAuth() {
  return window['go']['main']['App']['StartTwitchAuth']();
}

export function SyncRewards() {
  return window['go']['main']['App']['SyncRewards']();
}

export function TestAction(arg1, arg2) {
  return window['go']['main']['App']['TestAction'](arg1, arg2);
}

export function ToggleAction(arg1, arg2) {
  return window['go']['main']['App']['ToggleAction'](arg1, arg2);
}

export function UpdateAction(arg1) {
  return window['go']['main']['App']['UpdateAction'](arg1);
}
