// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {updater} from '../models';
import {main} from '../models';
import {starcitizen} from '../models';

export function AddCustomAction(arg1:config.Action):Promise<config.Action>;

export function BrowseSCDir():Promise<string>;

export function CheckForUpdate():Promise<updater.Release>;

export function ConnectTwitch():Promise<void>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteAllRewards():Promise<void>;

export function DisconnectTwitch():Promise<void>;

export function GetActions():Promise<Array<config.Action>>;

export function GetBindStatus():Promise<Array<main.BindStatus>>;

export function GetConfig():Promise<config.Config>;

export function GetCooldownRemaining(arg1:string):Promise<number>;

export function GetDebugLogPath():Promise<string>;

export function GetGlobalEnable():Promise<boolean>;

export function GetInputMode():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLockedKeys():Promise<Array<string>>;

export function GetSCChannel():Promise<string>;

export function GetSCDir():Promise<string>;

export function GetSCInstalls():Promise<Array<starcitizen.Install>>;

export function GetTwitchApp():Promise<main.TwitchApp>;

export function GetTwitchChannel():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportSCBinds():Promise<number>;

export function InstallUpdate():Promise<void>;

export function IsGameRunning():Promise<boolean>;

export function IsTwitchConnected():Promise<boolean>;

export function RemoveSCBinds():Promise<number>;

export function SetGlobalEnable(arg1:boolean):Promise<void>;

export function SetInputMode(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetSCDir(arg1:string):Promise<void>;

export function SetTargetWindow(arg1:string):Promise<void>;

export function SetTwitchApp(arg1:string,arg2:string):Promise<void>;

export function StartTwitchAuth():Promise<main.DeviceAuthInfo>;

export function SyncRewards():Promise<void>;

export function TestAction(arg1:string,arg2:number):Promise<void>;

export function ToggleAction(arg1:string,arg2:boolean):Promise<void>;

export function UpdateAction(arg1:config.Action):Promise<void>;
